"""Type stubs for the _cuda_corr C++/CUDA extension (built at install time)."""

from torch import Tensor

def forward(fmap1: Tensor, fmap2: Tensor, coords: Tensor, ii: Tensor, jj: Tensor, radius: int) -> tuple[Tensor]: ...
def backward(fmap1: Tensor, fmap2: Tensor, coords: Tensor, ii: Tensor, jj: Tensor, grad: Tensor, radius: int) -> tuple[Tensor, Tensor]: ...
def patchify_forward(net: Tensor, coords: Tensor, radius: int) -> tuple[Tensor]: ...
def patchify_backward(net: Tensor, coords: Tensor, grad: Tensor, radius: int) -> tuple[Tensor]: ...
