"""FISHEYE624 and SE3 against what projectaria-tools 2.3 computes on real Aria calibrations.

``packages/kornia-staging/fixtures/cameras/fisheye624_projectaria.json`` holds four factory cameras (HOT3D's
Aria Gen1 and the Aria Gen2 Pilot Dataset, a SLAM camera and the RGB camera of
each) with, generated by the SDK: projections of sampled points (``null`` where
``CameraCalibration.project`` returns nothing), unprojections of sampled pixels,
the quarter-turn calibration, the rescaled calibration, and the pose matrices.
Every comparison is exact: the module repeats the SDK's arithmetic in its order.
"""

import json
import math
from pathlib import Path

import numpy as np
import pytest
from jaxtyping import Float64
from numpy import ndarray

from simplecv.camera_parameters import Fisheye624Parameters
from simplecv.se3 import SE3
from simplecv.sensors.camera import fisheye624

FIXTURE: Path = Path(__file__).parents[2] / "kornia-staging" / "fixtures" / "cameras" / "fisheye624_projectaria.json"
CAMERAS: list[dict] = json.loads(FIXTURE.read_text())["cameras"]


def expected(rows: list[list[float] | None], width: int) -> Float64[ndarray, "n d"]:
    """SDK outputs with ``None`` (no projection) as a NaN row."""
    return np.array([[np.nan] * width if row is None else row for row in rows], dtype=np.float64)


def camera_of(entry: dict) -> Fisheye624Parameters:
    pose: dict = entry["device_T_camera"]
    return Fisheye624Parameters(
        name=entry["label"],
        width=entry["width"],
        height=entry["height"],
        params=np.array(entry["params"], dtype=np.float64),
        rig_T_cam=SE3.from_quaternion(np.array(pose["quaternion_wxyz"], dtype=np.float64), np.array(pose["translation"], dtype=np.float64)),
        max_solid_angle=entry["max_solid_angle"],
        valid_radius=entry["valid_radius"],
    )


@pytest.fixture(params=CAMERAS, ids=[f"{entry['source']}:{entry['label']}" for entry in CAMERAS])
def entry(request: pytest.FixtureRequest) -> dict:
    return request.param


def test_projection_is_the_sdks_bit_for_bit(entry: dict) -> None:
    pixels: Float64[ndarray, "n 2"] = fisheye624.project(camera_of(entry), np.array(entry["points_cam"], dtype=np.float64))
    np.testing.assert_array_equal(pixels, expected(entry["expected_pixels"], 2))
    assert np.isnan(pixels).any() and np.isfinite(pixels).any(), "the samples cover both visible and rejected points"


def test_unprojection_is_the_sdks_bit_for_bit(entry: dict) -> None:
    rays: Float64[ndarray, "n 3"] = fisheye624.unproject(camera_of(entry), np.array(entry["pixels"], dtype=np.float64))
    np.testing.assert_array_equal(rays, expected(entry["expected_rays"], 3))


def test_unprojection_inverts_projection(entry: dict) -> None:
    camera: Fisheye624Parameters = camera_of(entry)
    points: Float64[ndarray, "n 3"] = np.array(entry["points_cam"], dtype=np.float64)
    pixels: Float64[ndarray, "n 2"] = fisheye624.project(camera, points)
    visible = np.isfinite(pixels).all(axis=1)
    rays: Float64[ndarray, "n 3"] = fisheye624.unproject(camera, pixels[visible])
    np.testing.assert_allclose(rays[:, :2], points[visible, :2] / points[visible, 2:], rtol=0.0, atol=1e-8)


def test_pose_matrix_is_the_sdks_bit_for_bit(entry: dict) -> None:
    np.testing.assert_array_equal(camera_of(entry).rig_T_cam.matrix(), np.array(entry["expected_device_T_camera"]))


def test_quarter_turn_is_the_sdks_bit_for_bit(entry: dict) -> None:
    rotated: Fisheye624Parameters = fisheye624.rotate_cw90(camera_of(entry))
    turn: dict = entry["expected_cw90"]
    assert (rotated.width, rotated.height) == (turn["width"], turn["height"]) == (entry["height"], entry["width"])
    np.testing.assert_array_equal(rotated.params, np.array(turn["params"]))
    np.testing.assert_array_equal(rotated.rig_T_cam.matrix(), np.array(turn["device_T_camera"]))
    np.testing.assert_array_equal(fisheye624.project(rotated, np.array(entry["points_cam"], dtype=np.float64)), expected(turn["pixels"], 2))


def test_rescale_is_the_sdks_bit_for_bit() -> None:
    rescaled: list[dict] = [entry for entry in CAMERAS if "rescale" in entry]
    assert len(rescaled) == 2
    for entry in rescaled:
        target: dict = entry["rescale"]
        camera: Fisheye624Parameters = fisheye624.rescale(
            camera_of(entry), width=target["width"], height=target["height"], scale=target["scale"], origin_offset=tuple(target["origin_offset"])
        )
        np.testing.assert_array_equal(camera.params, np.array(target["params"]))
        assert camera.valid_radius == target["valid_radius"]
        assert (camera.width, camera.height) == (target["width"], target["height"])


def test_to_fisheye62_drops_only_the_thin_prism_terms(entry: dict) -> None:
    camera: Fisheye624Parameters = camera_of(entry)
    approximate = camera.to_fisheye62()
    f, cx, cy, *radial_tangential = camera.params[:11]
    assert approximate.intrinsics.fl_x == approximate.intrinsics.fl_y == f
    assert (approximate.intrinsics.cx, approximate.intrinsics.cy) == (cx, cy)
    assert approximate.distortion is not None
    distortion = approximate.distortion
    assert [distortion.k1, distortion.k2, distortion.k3, distortion.k4, distortion.k5, distortion.k6, distortion.p1, distortion.p2] == radial_tangential
    np.testing.assert_array_equal(approximate.extrinsics.world_T_cam, camera.rig_T_cam.matrix())


def test_se3_composition_follows_rotation_and_translation() -> None:
    quarter_turn: SE3 = SE3.rot_z(math.pi / 2.0)
    shifted: SE3 = SE3.from_quaternion(np.array([1.0, 0.0, 0.0, 0.0]), np.array([1.0, 2.0, 3.0]))
    composed: SE3 = quarter_turn @ shifted
    np.testing.assert_allclose(composed.matrix(), quarter_turn.matrix() @ shifted.matrix(), atol=1e-15)
    np.testing.assert_allclose(composed.translation, [-2.0, 1.0, 3.0], atol=1e-15)
    np.testing.assert_allclose(np.linalg.norm(SE3.from_quaternion(np.array([2.0, 0.0, 0.0, 0.0]), np.zeros(3)).quaternion_wxyz), 1.0)


@pytest.mark.parametrize("angle_rad", [0.0, 1e-200, -1e-200, 1e-12, -1e-12])
def test_rot_z_takes_the_small_angle_branch(angle_rad: float) -> None:
    # Sophus's SO3::exp Taylor branch below epsilon squared: no division by theta, and 0.0 is the identity.
    rotation: SE3 = SE3.rot_z(angle_rad)
    np.testing.assert_array_equal(rotation.quaternion_wxyz, [1.0, 0.0, 0.0, 0.5 * angle_rad])
    np.testing.assert_array_equal(rotation.translation, np.zeros(3))
    if angle_rad == 0.0:
        np.testing.assert_array_equal(rotation.matrix(), np.eye(4))


def test_rot_z_above_epsilon_is_the_closed_form() -> None:
    angle_rad: float = 1e-6
    np.testing.assert_array_equal(SE3.rot_z(angle_rad).quaternion_wxyz, [math.cos(0.5 * angle_rad), 0.0, 0.0, math.sin(0.5 * angle_rad) / angle_rad * angle_rad])


def test_valid_radius_and_image_bounds_reject_pixels() -> None:
    camera: Fisheye624Parameters = Fisheye624Parameters(
        name="test",
        width=640,
        height=480,
        params=np.array([300.0, 320.0, 240.0, *([0.0] * 12)]),
        rig_T_cam=SE3.from_quaternion(np.array([1.0, 0.0, 0.0, 0.0]), np.zeros(3)),
        max_solid_angle=1.5,
        valid_radius=10.0,
    )
    points: Float64[ndarray, "3 3"] = np.array([[0.0, 0.0, 1.0], [0.5, 0.0, 1.0], [0.0, 0.0, -1.0]])
    pixels: Float64[ndarray, "3 2"] = fisheye624.project(camera, points)
    np.testing.assert_array_equal(pixels[0], [320.0, 240.0])
    assert np.isnan(pixels[1:]).all()
